dist: trusty
sudo: required

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  # gcc-avr, avr-libc
  - sudo add-apt-repository -y ppa:pmjdebruijn/gcc-avr-release
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y gcc-avr avr-libc

  # srec_cat
  - sudo apt-get install -qq -y srecord

  # avra
  - git clone https://github.com/mnaberez/avra.git
  - make -C avra/src -f makefiles/Makefile.linux
  - export PATH=$PATH:$PWD/avra/src

  # as740, as78k0, asf2mc8, aslink
  - wget -q -U travis http://6502.org/tools/asm/asxs5p30.zip
  - unzip -q asxs5p30.zip
  - make -C asxv5pxx/asxmak/linux/build as740 as78k0 asf2mc8 aslink
  - export PATH=$PATH:$PWD/asxv5pxx/asxmak/linux/build

script:
  - make -C faceplate_emulator/firmware
  - python faceplate_emulator/host/setup.py test -q
  - make -C kwp1281_tool/firmware
  - make -C reverse_engineering/vw_gamma_5_technisat/disasm
  - make -C reverse_engineering/vw_premium_4_clarion/disasm/pu1666a_mainmcu
  - make -C reverse_engineering/vw_premium_4_clarion/disasm/pu1666a_submcu
  - make -C reverse_engineering/vw_rhapsody_technisat/disasm
  - make -C volume_monitor/firmware
  - make -C tape_emulator/firmware
