dist: trusty

language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    sources:
      - sourceline: 'ppa:pmjdebruijn/gcc-avr-release'
    packages:
      - avr-libc
      - gcc-avr
      - srecord

before_install:
  # avra
  - git clone https://github.com/mnaberez/avra.git
  - make -C avra/src -f makefiles/Makefile.linux
  - export PATH=$PATH:$PWD/avra/src

  # asxxxx
  - git clone https://github.com/mnaberez/asxxxx.git
  - make -C asxxxx/asxv5pxx/asxmak/linux/build all
  - export PATH=$PATH:$PWD/asxxxx/asxv5pxx/asxmak/linux/build

script:
  - make -C faceplate_emulator/firmware
  - python faceplate_emulator/host/setup.py test -q
  - make -C kwp1281_tool/firmware
  - make -C reverse_engineering/vw_gamma_5_technisat/disasm
  - make -C reverse_engineering/vw_premium_4_clarion/disasm/pu1666a_mainmcu
  - make -C reverse_engineering/vw_premium_4_clarion/disasm/pu1666a_submcu
  - make -C reverse_engineering/vw_premium_5_delco/disasm
  - make -C reverse_engineering/vw_premium_5_delco/dumpram
  - make -C reverse_engineering/vw_premium_5_delco/remote
  - make -C reverse_engineering/vw_rhapsody_technisat/disasm
  - make -C volume_monitor/firmware
  - make -C tape_emulator/firmware
